# Bases du langage Python

Instructions de base

In [1]:
print(1)
1 + 1
3E5
var = ["bonjour",7, 3.14]
a, b, c = 1, 2, 3 # affectation de variable

x = 1; y = 2

1

In [2]:
print('bonjour # 123')

bonjour # 123

In [3]:
x = 1; y = 2

In [4]:
var = ["bonjour",7, 3.14]

In [5]:
print(var)

['bonjour', 7, 3.14]

In [6]:
var[1] = 3

In [7]:
var

['bonjour', 3, 3.14]

In [57]:
import random as rd

In [58]:
rd.random()

0.8502546296116176

In [8]:
len(var)

3

In [9]:
var[len(var)-1]

3.14

In [10]:
var[0][-1]

'r'

In [11]:
print(var)

['bonjour', 3, 3.14]

In [12]:
x = 3.5

In [13]:
print(var[0][1:4])

onj

In [14]:
for i in var:
    print(i)

bonjour
3
3.14

In [15]:
from math import sqrt, sin, pi
import random as rd

In [16]:
sqrt(16)

4.0

In [17]:
sin(pi/2)

1.0

Attention, dans un notebook, si on veut afficher la valeur d'une variable, il faut écrire explicitement `print(...)` sauf si l'affichage se fait sur la dernière ligne de la cellule.

In [18]:
x = 1
x
# Ici c'est bon, la valeur de x est affichée car on demande à l'afficher
# dans la dernière ligne de la cellue.

1

In [19]:
x = 1
# Dans cette cellule, si on veut que la valeur de x soit affichée,
# il faut rajouter print(x).
print(x)
y = 2

1

Commentaires

In [20]:
# Ceci est un commentaire
print('Bonjour') # ceci est un commentaire
print('Bonjour # tout le monde') # Affiche 'Bonjour # tout le monde'

x, y = 1, 2
# Ajouter y à x
x = x + y

Bonjour
Bonjour # tout le monde

Définir des variables

In [21]:
age = 16
name = 'toto'

Types de variables

In [22]:
x = 16546546
print(type(x))
y = 1.0
print(type(y))
z = "toto"
print(type(z))

<class 'int'>
<class 'float'>
<class 'str'>

In [23]:
x = str(x)

In [24]:
type(x)

str

In [25]:
x = "abc"
print(type(x))

<class 'str'>

In [26]:
a = 9
b= 3

In [27]:
a//b

3

In [28]:
a%b

0

# Objets Python

### Les listes (List)

In [29]:
# Création
x = [1, 4, 9, 16, 25]
print(len(x))

# Indexation
print(x[-1])
print(x[2:5])
print(x[2:])
print(x[:3])
print(x[::-1])

5
25
[9, 16, 25]
[9, 16, 25]
[1, 4, 9]
[25, 16, 9, 4, 1]

In [30]:
x[::-1]

[25, 16, 9, 4, 1]

In [31]:
print(x[::2])

[1, 9, 25]

In [32]:
8 not in x

True

In [33]:
print(4 in x[1::2])

True

In [34]:
len(x[1::2])

2

In [35]:
# Opérateurs
print(4 in x)
print(5 in x)

# Concaténation
y = [1, 4, 9] + [16, 25, 36]
print(y)

# Réplication
print(x*2)

# Fonctions sur listes
print(len(x))
print(min(x), max(x))

True
False
[1, 4, 9, 16, 25, 36]
[1, 4, 9, 16, 25, 1, 4, 9, 16, 25]
5
1 25

In [36]:
x.append(36)

In [37]:
# Les listes sont modifiables (mutables en anglais)
z = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
z[2] = 10
print(z)

# Modifier un élément en utilisant son indice dans la liste
z[3] = 21
print(z)

# Ajouter un élément
# À la fin de la liste
z.append(10)
print(z)
# À une position précise dans la liste
z.insert(4, 30)
print(z)

# Supprimer un élément
# Supprimer la première instance de la valeur 10
z.remove(10)
print(z)
# Supprimer l'élément d'indice 4 (= 5ème position)
del z[4]
print(z)

[0, 1, 10, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 10, 21, 4, 5, 6, 7, 8, 9]
[0, 1, 10, 21, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 10, 21, 30, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 21, 30, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 21, 30, 5, 6, 7, 8, 9, 10]

In [38]:
x = [1, 4, 9, 16, 25]

In [39]:
x

[1, 4, 9, 16, 25]

In [40]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [41]:
if 10 == x[4]:
    print(True)
else:
    print(False)

False

In [42]:
list_c = [1,1,2,3,1,1,0]
a_supprimer = 1

In [43]:
tup_c = (1,1,2,3,1,1,0)

In [44]:
len(list_c)

7

In [45]:
count = 0
for i in range(len(list_c)):
    if list_c[i]==a_supprimer:
        count+=1 # count = count + 1
print(count)

4

In [46]:
list_c.count(a_supprimer)

4

In [47]:
list_c

[1, 1, 2, 3, 1, 1, 0]

In [48]:
for i in range(count):
    list_c.remove(a_supprimer)

In [49]:
list_new = []
for i in range(len(list_c)):
    if list_c[i]!=a_supprimer:
        list_new.append(list_c[i])
print(list_new)

[2, 3, 0]

In [50]:
list_new = []
for elt_list in list_c:
    if elt_list != a_supprimer:
        list_new.append(elt_list)
print(list_new)

[2, 3, 0]

In [51]:
from module import suppr_element

In [52]:
suppr_element(list_c, a_supprimer)

[2, 3, 0]

In [ ]:
new_list_c = suppr_element(list_c, 1)
print(new_list_c)

In [ ]:
suppr_element(new_list_c, 2)

In [ ]:
[elt_list for elt_list in list_c if elt_list != a_supprimer]

In [ ]:
def effet_de_bord_liste(input_list):
    """
    Attention aux types mutables. Ils peuvent être modifiés par une fonction sans être retournés.
    """
    #input_list = list(input_list)
    print(f"Original list: {input_list}")
    input_list.append(42)  # Modifying the mutable object
    print(f"Modified list: {input_list}")

# Example usage
effet_de_bord_liste(x)
print(f"List after function call: {x}")

In [ ]:
def effet_de_bord_liste(input_int):
    """
    Attention aux types mutables. Ils peuvent être modifiés par une fonction sans être retournés.
    """
    print(f"Original int: {input_int}")
    input_int = input_int + 10
    print(f"Modified int: {input_int}")

# Example usage
val = 5
effet_de_bord_liste(val)
print(f"int after function call: {val}")

**La compréhension de liste**

Un outil très puissant pour du code concis

In [ ]:
# Sans compréhension de liste
squares = []
for n in range(7):
  squares.append(n**2)
print(squares)

# Avec compréhension de liste
squares = [n**2 for n in range(7)]
print(squares)

Les ensembles (set)

In [ ]:
print(set([1, 2, 2, 3, 5, 5]))
basket = {'pomme', 'orange', 'pomme', 'poire', 'orange', 'banane'}
print(basket) # doublons enlevés
print('ananas' in basket)

Les dictionnaires (dict)

In [ ]:
people_dict = {
    'alan': {'age': 30, 'height': 1.72},
    'monica': {'age': 31, 'height': 1.65},
}
print(people_dict['monica'])
print(people_dict['monica']['age'])
people_dict['alan'] = {'age': 32, 'height': 1.72}
people_dict['alan']['age'] = 32

In [ ]:
people_dict["john"] = {"height": 1.80}

In [ ]:
people_dict["john"]["age"]

In [ ]:
people_dict["alan"]

In [ ]:
print('alan' in people_dict)
print('age' in people_dict)
print(len(people_dict))
print(min(people_dict))
print(max(people_dict))

In [ ]:
people_dict.keys()

In [ ]:
for key, value in people_dict.items():
    try:
        print(key, value["age"])
    except KeyError:
        print(key, "n'a pas d'âge enregistré")

In [ ]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
  print(k, v)

In [ ]:
exo_dict = {
    'alan': {'age': 30, 'height': 1.72},
    'monica': {'age': 31, 'height': 1.65},
    'effectif': 45,
    52: "test"
}

In [ ]:
for k,v in exo_dict.items():
    print(k, type(v))
    if type(v) is dict:
        for k2,v2 in v.items():
            print("    ", k2,type(v2))

In [ ]:
for k,v in people_dict.items():
    print(k, type(v))

In [ ]:
import numpy as np

Exercices

In [ ]:
list_exo = list(np.arange(10))

In [ ]:
list_exo

In [ ]:
[list_exo[0]]+list_exo

In [ ]:
# Echanger le 1 et les dernier element de la liste
print(list_exo[0])
print(list_exo[-1])
#list_exo = [list_exo[-1]] + list_exo[1:-1] + [list_exo[0]]
list_exo[0], list_exo[-1] = list_exo[-1], list_exo[0]
print(list_exo)

In [ ]:
first = list_exo[0]
last = list_exo[-1]
new_list = []
for i in range(len(list_exo)):
    if i==0:
        new_list.append(last)
    elif i==len(list_exo)-1:
        new_list.append(first)
    else:
        new_list.append(list_exo[i])
print(new_list)

In [ ]:
# compter le nombre d'occurences d'un élément dans une liste
elt = 1
n_elt = 0
list_exo_2 = list_exo*3
for l_elt in list_exo_2:
    if l_elt == elt:
        n_elt+=1
print(n_elt)

In [ ]:
# supprimer les occurences d'un élément dans une liste
elt = 1
list_exo_2 = list_exo*2
list_resultat = []
for list_elt in list_exo_2:
    if list_elt != elt:
        list_resultat.append(list_elt)
print(list_resultat)

In [ ]:
# supprimer les occurences d'un élément dans une liste
elt = 1
list_exo_2 = list_exo*2
list_resultat = []
i=0
while i< len(list_exo_2):
    if list_exo_2[i] == elt:
        del list_exo_2[i]
    else:
        i+=1

print(list_exo_2)

In [ ]:
[l_elt for l_elt in list_exo_2 if l_elt!=elt]

In [ ]:
list_bool = [True if l_elt%2==0 else False for l_elt in list_exo]
# compter le nombre d'occurences d'un élément dans une liste
elt = False
n_elt = 0
for l_elt in list_bool:
    if l_elt == elt:
        n_elt+=1
print(n_elt)

In [ ]:
# compter le nombre d'occurences d'un élément pair dans une liste
n_elt = 0
for l_elt in list_exo:
    if l_elt%2==0:
        n_elt+=1
print(n_elt)

In [ ]:
len(list_exo)-n_elt

In [54]:
x=0
while x<3:
    # if x==2:
    #     break
    x+=1
print(x)

3

In [56]:
list(range(0,16,3))

[0, 3, 6, 9, 12, 15]

# Les fonctions

In [ ]:
def fibonacci(x):
  a, b = 0, 1
  if x < 0:
    return "x must be a positive integer!"
  for i in range(x):
    a, b = b, a+b
  return a

Paramètres par défaut

In [ ]:
def exponent(x, expnt = 2) -> float:
  '''
  Returns x to the power of expnt. By defaut returns x**2.
  '''
  return x**expnt #pow(x,expnt)

In [61]:
exponent(4,3)

64

## Les exceptions

In [62]:
import numpy as np

In [68]:
def divide_numbers(x, y):
  '''
  Divise y par x et renvoie le résultat.
  '''
  try:
    # On essaie de faire la division
    z = y / x
  except:
    # Sinon on rattrape l'erreur
    print("Erreur : impossible de diviser par zéro !")
    return "ERREUR"
  return z

In [70]:
divide_numbers("abc", 3)

Erreur : impossible de diviser par zéro !

'ERREUR'

In [ ]:
text = "Bonjour tout le monde !"

In [ ]:
len(text)

In [96]:
names = ['Tom', 'Lea', 'Martin', 'Sylvain', 'Philippe']
def keep_long_names(name_list, min_length=3):
    return [l_elt for l_elt in name_list if len(l_elt)>min_length]

def keep_long_names2(name_list, min_length=3):
    result = []
    for l_elt in name_list:
        if len(l_elt)>min_length:
            result.append(l_elt)
    return result

print(keep_long_names(names, min_length=6))
print(keep_long_names(names))

['Sylvain', 'Philippe']
['Martin', 'Sylvain', 'Philippe']

In [ ]:
list_long_names = keep_long_names(names, min_length=3)

In [ ]:
def nombres_premiers(n_max):
    list_premier = []
    for i in range(2, n_max+1):
        est_premier = True
        for j in range(2, i):
            if i % j == 0:
                est_premier = False
                break
        if est_premier:
            list_premier.append(i)
    return list_premier

In [ ]:
np.array(nombres_premiers(100))

# Pandas : DataFrames

### Définition et opérations courantes

In [73]:
import pandas as pd

# Définir un DataFrame vide
#df = pd.DataFrame(data=None, index=None, columns=None, dtype=None)

# Définir un DataFrame à partir d'un objet rempli
df = pd.DataFrame(data=np.array([[3, 2, 0, 1], [0, 3, 7, 2]]).T, columns=['apples', 'oranges'])

# # À partir d'un dictionnaire
# data = {
#     'apples': [3, 2, 0, 1],
#     'oranges': [0, 3, 7, 2]
# }
# df = pd.DataFrame(data)

In [74]:
df

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [77]:
df[df['apples'] > 1]

   apples  oranges
0       3        0
1       2        3

In [84]:
print(df.tail(n=2))

   apples  oranges
2       0        7
3       1        2

In [78]:
# Structure d'un DataFrame
type(df)
df.dtypes
df.ndim
df.shape
df.size

# Afficher les premières ou dernières lignes
df.head()
df.head(n=2)
df.tail()

# Renommer les colonnes
df.rename(columns={'apples': 'a', 'oranges': 'o'})

# Opérations sur colonnes
df.sum()
df.count()
df.median()
df.quantile([0.25, 0.75])
df.mean()
df.min()
df.max()
df.var()
df.std()
df.describe()
df.describe().T # transpose for better visualisation
df.describe(percentiles=[0.3, 0.5, 0.7])
df.info(show_counts=True, memory_usage=True, verbose=True)

# Opérations sur lignes
# Les méthodes précédentes agissent par défaut sur les colonnes.
# Pour les faire agir sur les lignes, on remplace l'argument `axis` :
df.sum(axis=1)

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   apples   4 non-null      int64
 1   oranges  4 non-null      int64
dtypes: int64(2)
memory usage: 196.0 bytes

0    3
1    5
2    7
3    3
dtype: int64

### Sélection de colonnes et/ou lignes

**Colonnes**

In [ ]:
print(df.columns)

Index(['apples', 'oranges', 'bananas'], dtype='str')

In [87]:
# Liste des colonnes
print(df.columns)

# Sélectionner une colonne
df['apples']
df.apples # de type pandas.core.series.Series

# Ajouter une nouvelle colonne
df['bananas'] = [5, 1, 3, 0]

# Sélectionner plusieurs colonnes
df[['apples', 'bananas']]

Index(['apples', 'oranges', 'bananas'], dtype='str')

   apples  bananas
0       3        5
1       2        1
2       0        3
3       1        0

In [ ]:
names = ["joe", "pierre","jeanne","sylvie"]

In [94]:
df['clients'] = names

In [95]:
df

   apples  oranges  bananas clients
0       3        0        5    jean
1       2        3        1  pierre
2       0        7        3  jeanne
3       1        2        0  sylvie

In [101]:
df[df['clients'].isin(keep_long_names(df['clients'], min_length=4))]

   apples  oranges  bananas clients
1       2        3        1  pierre
2       0        7        3  jeanne
3       1        2        0  sylvie

In [ ]:
df["total fruits"] = df[["apples","bananas","oranges"]].sum(axis=1)

In [ ]:
df[["apples","bananas","oranges"]].sum(axis=0)

In [ ]:
df = df.append({"clients":"total", "apples":df["apples"].sum(), "bananas":df["bananas"].sum(), "oranges":df["oranges"].sum(), "total fruits":df["total fruits"].sum()}, ignore_index=True)

In [ ]:
df[df["clients"]=='Lea']

In [ ]:
df.loc[1:3,["apples", "bananas"]]

In [ ]:
df[df['clients'].isin(keep_long_names(df['clients'], min_length=3))]

**Lignes**

In [ ]:
# Sélectionner une ligne par son indice de ligne
df[df.index == 1]
df.loc[1]

# Plusieurs lignes
df[df.index.isin([0, 2, 3])]
df[df.index.isin(range(2,4))]

# En utilisant iloc (utile si les indices sont complexes)
df.iloc[1]
df.iloc[1:4]
df.iloc[[0, 2, 3]]

In [ ]:
df.loc[1, 'bananas']

**Colonnes et lignes**

In [ ]:
df.loc[2:4, ['apples', 'bananas']]
df.iloc[[0, 2, 3], [0, 2]]

# loc peut prendre une condition en argument
df.loc[df['apples'] >= 2]

# Modifier les valeurs
df.loc[df['apples'] == 3, ['apples']] = 4
df

In [ ]:
# Sélection avec condition
print(df[df.apples >= 3])
print(df.loc[df.apples >= 3])

# Négation
df[~(df.apples >= 3)]

In [ ]:
# Add line to dataframe (specify line index, will be added at the end)
df.loc[4] = [2, 3, 4]
# Sort by line index
df = df.sort_index().reset_index(drop=True)
df

## Gérer les valeurs manquantes

Rajoutons des valeurs manquantes pour voir comment en pratique les gérer avec pandas :

In [ ]:
df.loc[[1, 4], 'apples'] = np.NaN
df.loc[2, 'oranges'] = np.NaN
print(df)

In [ ]:
# Vérifier la présence de données manquantes
df.isnull() # dataframe de booléens [i, j] = True si df[i, j] est manquant, False sinon
df.isnull().any() # Indique si des valeurs manquantes sont présentes dans chaque colonne
df.isnull().sum() # Donne le nombre de données manquantes dans chaque colonne

In [ ]:
df.fillna(0)

In [ ]:
df.dropna(axis=1)

In [ ]:
# Supprimer les données manquantes
# NB : utile de copier d'abord le dataframe avant toute opération de modification...
df2 = df.copy()
df2.dropna() # supprime les lignes avec valeurs manquantes
# df2.dropna(inplace=True) # idem, en enregistrant les modifications
df2.dropna(axis=1) # supprime les colonnes avec valeurs manquantes
df2.dropna(how='all') # supprime les lignes et les colonnes avec valeurs manquantes
# df2.dropna(['apples'])

In [ ]:
# Remplacer les données manquantes
df3 = df.copy()
df3.fillna(value=-1, inplace=True)
df3

## Agréger les données avec `groupby`

In [ ]:
# Données médicales pour 4 individus prises sur deux années différentes :
#   nom, sexe, poids et nombre d'accidents au cours de l'année précédente.
df = pd.DataFrame(
    {
        'name': ['Mark', 'Kevin', 'Sofia', 'Philip', 'Mark', 'Kevin', 'Sofia', 'Philip'],
        'year': ['Y1', 'Y1', 'Y1', 'Y1', 'Y2', 'Y2', 'Y2', 'Y2'],
        'gender': ['M', 'M', 'F', 'M', 'M', 'M', 'F', 'M'],
        'height': [177, 201, 163, 178, 177, 201, 163, 178],
        'weight': [65, 87, 52, 72, 63, 92, 55, 68],
        'accidents': [2, 1, 1, 0, 0, 3, 0, 3],
    }
)
df

In [ ]:
df.groupby("year").mean()

In [ ]:
# Moyenner sur toutes les colonnes
# Par défaut les colonnes non-numériques sont sautées
df.groupby('name').mean()

In [ ]:
# Moyenner sur 'weight' et sommer sur 'accidents'
df2 = df.copy()
df2 = df2.groupby('name').agg({
    'weight': 'mean',
    'accidents': 'sum'
    })

In [ ]:
df2

## Utiliser la fonctionnalité `apply`

In [ ]:
# Catégoriser en fonction du nombre d'accidents
def categorise_accidents(n):
  if n <= 1:
    return 'low'
  elif n <= 3:
    return 'medium'
  else:
    return 'high'

In [ ]:
df2["category_accident"] = df2["accidents"].apply(categorise_accidents)
df2

In [ ]:
df2["category_accident"] = df2["accidents"].apply(lambda x: 'low' if x <= 1 else 'medium' if x <= 3 else 'high')
df2

In [ ]:
# Convertir le poids en livres (lb)
def kg_to_pound(x):
  return x / 0.454
kg_to_pound(10)

In [ ]:
df.rename(columns={'weight': 'weight_kg'}, inplace=True)
df["weight_lb"] = df["weight_kg"].apply(kg_to_pound)
df

Calculons maintenant l'IMC de chacun.

IMC = weight_kg / height [m] ** 2

In [ ]:
def calc_imc(w, h):
  return w / (h / 100)**2

In [ ]:
df["imc"] = df[['weight_kg','height']].apply(lambda x: calc_imc(x['weight_kg'], x['height']), axis=1)
df

# Visualisation de données

## Introduction à matplotlib

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
x = np.arange(0.0, 2.0, 0.01)
y = 1 + np.sin(2 * np.pi * x)

In [ ]:
len(y)

In [ ]:
plt.plot(x, y)
plt.xlabel('Time (s)')
plt.ylabel('Voltage (mV)')
plt.title('Notre permier graphe')
plt.grid(True)
# plt.savefig("test.png" # si on veut enregistrer la figure
plt.show()

Voyons maintenant quelques arguments simples pour changer l'apparence de notre figure :

In [ ]:
plt.plot(x, y, linestyle='--', color='red', linewidth=3)
plt.xlabel('Time (s)', fontsize=16, labelpad=15)
plt.ylabel('Voltage (mV)', fontsize=16, labelpad=15)
plt.xlim([-0.3, 2.3])
plt.ylim([-0.5, 2.2])
plt.title('Our second plot', fontsize=20, pad=20)
plt.grid(True, linestyle='--', color='gray')
plt.show()

Il est également facile d'ajouter une légende à la figure :

In [ ]:
plt.plot(x, y, linestyle='--', color='red', linewidth=3, label='First series')
plt.plot(x, 1 + np.cos(2 * np.pi * x), linestyle='-.', color='blue', linewidth=3, label='Second series')
plt.xlabel('Time (s)', fontsize=16, labelpad=15)
plt.ylabel('Voltage (mV)', fontsize=16, labelpad=15)
plt.xlim([0, 2])
plt.ylim([-0.5, 2.2])
plt.title('Our second plot', fontsize=20, pad=20)
plt.grid(True, linestyle='--', color='gray')
plt.legend(loc='lower left', fontsize=14, framealpha=0.9)
plt.show()

À présent, explorons les axes de la figure : comment créer des axes multiples et gérer chaque axe indépendamment.

In [ ]:
# Créer un objet figure
fig = plt.figure(figsize=(8, 6))
# Créons des axes explicites
ax0 = fig.add_axes([0.1, 0.6, 0.8, 0.4])
ax0.plot(x, y, 'k+', label='First series')
ax1 = fig.add_axes([0.1, 0.05, 0.8, 0.4])
ax1.plot(x, 1 + np.cos(2 * np.pi * x), 'b+', label='Second series')
# Les propriétés de chaque axe peuvent être définies
# indépendamment.
ax0.set_xlabel('Time 0 (s)', fontsize=14, labelpad=12)
ax0.set_ylabel('Voltage 0 (mV)', fontsize=14, labelpad=12)
ax1.set_xlabel('Time 1 (s)', fontsize=14, labelpad=12, color='b')
ax1.set_ylabel('Voltage 1 (mV)', fontsize=14, labelpad=12, color='b')
ax0.set_xlim([-0.3, 2.3])
ax0.set_ylim([-0.5, 2.2])
ax0.set_title('First panel', fontsize=20, pad=20)
ax1.set_title('Second panel', fontsize=10, pad=5)
ax0.grid(True, linestyle='--', color='gray')
ax0.legend(loc='lower left', fontsize=14, framealpha=0.9)
plt.show()

Il existe également la méthode `subplots` qui permet de facilement générer des figures à plusieurs panels.

In [ ]:
# Créer un objet figure et les subplots associés
fig, axes = plt.subplots(2, 1, figsize=(8, 6))
# Nombre de lignes, nombre de colonnes
axes[0].plot(x, y, 'k+', label='First series')
axes[1].plot(x, 1 + np.cos(2 * np.pi * x), 'b+', label='Second series')
axes[0].set_xlabel('Time 0 (s)', fontsize=14, labelpad=12)
axes[0].set_ylabel('Voltage 0 (mV)', fontsize=14, labelpad=12)
axes[1].set_xlabel('Time 1 (s)', fontsize=14, labelpad=12, color='b')
axes[1].set_ylabel('Voltage 1 (mV)', fontsize=14, labelpad=12, color='b')
axes[0].set_xlim([-0.3, 2.3])
axes[0].set_ylim([-0.5, 2.2])
axes[0].set_title('First panel', fontsize=20, pad=20)
axes[1].set_title('Second panel', fontsize=10, pad=5)
axes[0].grid(True, linestyle='--', color='gray')
#axes[0].legend(loc='lower left', fontsize=14, framealpha=0.9)
#axes[1].legend(loc='lower left', fontsize=14, framealpha=0.9)
plt.show()

Matplotlib permet également d'afficher des graphiques type, comme les histogrammes :

In [ ]:
mu, sigma = 100, 15
x = mu + sigma * np.random.randn(10000)

plt.hist(x, bins=50, facecolor='g', alpha=0.75, density=True)
plt.xlabel('IQ')
plt.ylabel('Probability')
plt.title('Histogram of IQ')
plt.text(45, .025, r'$\mu=100,\ \sigma=15$', fontsize=16)
plt.axis([40, 160, 0, 0.03])
plt.grid(True)
plt.show()